import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from "antd";
import theme from "@/config/themeConfig";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { rubik } from "@/prisma/fonts";
import AuthProvider from "@/components/AuthProvider"
import RequireAuth from "@/components/RequireAuth";
import {MessageProvider} from "@/context/MessageContext"
import { App } from "antd";







// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <html lang="en">
      <body className={rubik.className}>
        <AuthProvider>
         <ConfigProvider theme={theme}>
          <AntdRegistry>
            <RequireAuth>
              <MessageProvider>
            <div className="main-container">
            <Header/>
            <App>
            <main className="flex-grow">{children}</main>
            </App>
            <Footer/>
            </div>
            </MessageProvider>
            </RequireAuth>
          </AntdRegistry>
        </ConfigProvider> 
        </AuthProvider>
       </body>
     </html>
  );
}
